# Generated by Django 3.0.6 on 2020-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inputEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='inputZip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='inputcaketype',
            field=models.CharField(max_length=500),
        ),
    ]
