# Generated by Django 3.0.6 on 2020-05-14 08:56

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200513_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='inputQuantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='inputZip',
        ),
        migrations.AlterField(
            model_name='order',
            name='inputPhonenumber',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
