# Generated by Django 3.0.6 on 2020-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200514_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inputPhonenumber',
            field=models.FloatField(),
        ),
    ]
