# Generated by Django 3.0.6 on 2020-05-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200514_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='inputAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='inputCity',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='inputComments',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='inputEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='inputPhonenumber',
            new_name='Phonenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='inputState',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='inputcaketype',
            new_name='caketype',
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.FloatField(default='1.5'),
        ),
    ]
